const diseaseData = {
  diabetes: {
    title: 'Diabetes (Type 2 focus)',
    aliases: ['diabetes', 'type 2 diabetes', 'high sugar', 'blood sugar', 'glucose', 'hba1c', 'prediabetes'],
    symptoms: ['Frequent urination', 'Excessive thirst', 'Fatigue', 'Blurred vision', 'Slow wound healing'],
    management: ['Balanced low-glycemic diet', 'Regular activity 150+ min/week', 'Weight management', 'Glucose monitoring as advised'],
    tests: ['Fasting plasma glucose', 'HbA1c', 'Postprandial glucose', 'Kidney function', 'Urine microalbumin'],
    medications: [
      { name: 'Metformin', dosage: '500-2000 mg', frequency: '2-3 times daily with meals', purpose: 'First-line agent, improves insulin sensitivity' },
      { name: 'SGLT2 Inhibitors (Dapagliflozin)', dosage: '5-10 mg', frequency: 'Once daily', purpose: 'Helps kidneys remove glucose via urine' },
      { name: 'GLP-1 Agonists (Semaglutide)', dosage: '0.5-2.4 mg', frequency: 'Once weekly', purpose: 'Reduces blood sugar and weight' }
    ],
    naturalRemedies: [
      { name: 'Cinnamon', dosage: '1-2 tsp or 1-2 grams', frequency: 'Daily with morning water', benefit: 'May improve insulin sensitivity' },
      { name: 'Turmeric (Curcumin)', dosage: '500-1000 mg', frequency: 'Once or twice daily', benefit: 'Anti-inflammatory, aids glucose control' },
      { name: 'Fenugreek', dosage: '5-10 grams seeds', frequency: 'Soak overnight, consume in morning', benefit: 'Known to lower blood sugar levels' },
      { name: 'Bitter Melon', dosage: '1-3 ounces juice', frequency: 'Once daily', benefit: 'Contains compounds similar to insulin' }
    ],
    prevention: ['Maintain healthy weight', 'Exercise regularly', 'Limit refined sugar', 'Annual screening if high risk'],
    redFlags: ['Persistent vomiting', 'Confusion', 'Dehydration', 'Very high glucose with drowsiness'],
  },
  hypertension: {
    title: 'Hypertension (High Blood Pressure)',
    aliases: ['hypertension', 'high blood pressure', 'high bp', 'bp'],
    symptoms: ['Often no symptoms', 'Headache', 'Dizziness', 'Blurred vision', 'Chest discomfort'],
    management: ['Low-sodium DASH diet', 'Weight reduction', 'Routine BP logs', 'Limit alcohol and stop smoking'],
    tests: ['Repeated BP checks', 'Kidney profile', 'ECG', 'Urine protein', 'Lipid profile'],
    medications: [
      { name: 'Lisinopril (ACE Inhibitor)', dosage: '10-40 mg', frequency: 'Once daily', purpose: 'Relaxes blood vessels to lower pressure' },
      { name: 'Amlodipine (Calcium Channel Blocker)', dosage: '5-10 mg', frequency: 'Once daily', purpose: 'Relaxes muscles in blood vessel walls' },
      { name: 'Hydrochlorothiazide (Thiazide)', dosage: '12.5-25 mg', frequency: 'Once daily, morning', purpose: 'Reduces fluid in body' }
    ],
    naturalRemedies: [
      { name: 'Garlic Extract', dosage: '600-900 mg', frequency: 'Daily in divided doses', benefit: 'May help lower systolic BP by 5-10 mmHg' },
      { name: 'Hibiscus Tea', dosage: '1-2 cups', frequency: 'Daily', benefit: 'Contains anthocyanins that relax arteries' },
      { name: 'Potassium-rich foods (Banana, Spinach)', dosage: 'Daily intake', frequency: '2-3 servings', benefit: 'Balances sodium and lowers BP' },
      { name: 'Magnesium Supplement', dosage: '300-400 mg', frequency: 'Once daily', benefit: 'Helps relax blood vessels' }
    ],
    prevention: ['Less salt', 'Regular exercise', 'Stress management', 'Routine BP checks'],
    redFlags: ['BP around/above 180/120 with symptoms', 'Chest pain', 'Neurologic deficit', 'Severe shortness of breath'],
  },
  asthma: {
    title: 'Asthma',
    aliases: ['asthma', 'wheeze', 'wheezing', 'inhaler asthma'],
    symptoms: ['Wheezing', 'Breathlessness', 'Cough at night/early morning', 'Chest tightness'],
    management: ['Daily controller inhaler if prescribed', 'Rescue inhaler for flare', 'Trigger avoidance', 'Asthma action plan'],
    tests: ['Spirometry', 'Peak flow monitoring', 'Allergy testing when needed'],
    medications: [
      { name: 'Salbutamol Inhaler (Rescue)', dosage: '100 mcg per puff', frequency: '1-2 puffs as needed', purpose: 'Quick relief during asthma attacks' },
      { name: 'Fluticasone/Salmeterol (Controller)', dosage: '125-250 mcg', frequency: 'Twice daily', purpose: 'Prevents inflammation and symptoms' }
    ],
    naturalRemedies: [
      { name: 'Honey', dosage: '1-2 tsp', frequency: 'Before bed and morning', benefit: 'Soothes airways and reduces coughing' },
      { name: 'Ginger Tea', dosage: '1-2 grams grated ginger', frequency: 'Once or twice daily', benefit: 'Anti-inflammatory, opens airways' },
      { name: 'Turmeric Milk', dosage: '1/2 tsp turmeric', frequency: 'Warm milk at bedtime', benefit: 'Reduces inflammation in respiratory tract' }
    ],
    prevention: ['Avoid smoke and allergens', 'Vaccinations', 'Correct inhaler technique'],
    redFlags: ['Unable to speak full sentence', 'Blue lips/fingertips', 'No response to rescue inhaler'],
  },
  copd: {
    title: 'COPD',
    aliases: ['copd', 'chronic bronchitis', 'emphysema', 'smoker cough'],
    symptoms: ['Chronic cough', 'Sputum', 'Progressive breathlessness', 'Frequent chest infections'],
    management: ['Smoking cessation', 'Pulmonary rehab', 'Inhaler adherence', 'Infection prevention'],
    tests: ['Spirometry', 'Chest imaging', 'Pulse oximetry'],
    medications: ['LAMA/LABA bronchodilators', 'Inhaled steroids in selected cases'],
    prevention: ['Stop smoking', 'Avoid pollutants', 'Flu and pneumococcal vaccines'],
    redFlags: ['Breathlessness at rest', 'Confusion', 'Cyanosis', 'High fever with worsening cough'],
  },
  ckd: {
    title: 'Chronic Kidney Disease (CKD)',
    aliases: ['ckd', 'chronic kidney disease', 'kidney failure', 'renal disease'],
    symptoms: ['Fatigue', 'Swelling in legs', 'Appetite loss', 'Reduced urine changes'],
    management: ['BP and sugar control', 'Kidney-friendly diet', 'Medication review for nephrotoxins', 'Nephrology follow-up'],
    tests: ['Serum creatinine/eGFR', 'Urine albumin-creatinine ratio', 'Electrolytes', 'Kidney ultrasound'],
    medications: ['ACE inhibitor/ARB when appropriate', 'Diuretics', 'Phosphate binders in advanced CKD'],
    prevention: ['Control diabetes and BP', 'Avoid unnecessary painkillers', 'Hydration and follow-up testing'],
    redFlags: ['Very low urine output', 'Severe breathlessness', 'Confusion', 'Chest pain'],
  },
  cad: {
    title: 'Coronary Artery Disease',
    aliases: ['cad', 'coronary artery disease', 'heart blockage', 'angina', 'ischemic heart disease'],
    symptoms: ['Chest pressure on exertion', 'Breathlessness', 'Sweating', 'Pain radiating to jaw/arm'],
    management: ['Cardiac risk control', 'Structured exercise under guidance', 'Dietary cholesterol control', 'Smoking cessation'],
    tests: ['ECG', 'Echocardiogram', 'Stress test', 'Coronary imaging', 'Lipid profile'],
    medications: ['Antiplatelets', 'Statins', 'Beta blockers', 'Nitrates'],
    prevention: ['Control BP/sugar/lipids', 'Physical activity', 'No tobacco'],
    redFlags: ['Persistent chest pain >15 minutes', 'Fainting', 'Severe breathlessness'],
  },
  heart_failure: {
    title: 'Heart Failure',
    aliases: ['heart failure', 'cardiac failure', 'congestive heart failure', 'chf'],
    symptoms: ['Breathlessness', 'Leg swelling', 'Night-time breathlessness', 'Fatigue'],
    management: ['Salt and fluid plan', 'Daily weight tracking', 'Medication adherence', 'Cardiology follow-up'],
    tests: ['Echocardiogram', 'BNP/NT-proBNP', 'ECG', 'Kidney function'],
    medications: ['ACE inhibitors/ARBs/ARNI', 'Beta blockers', 'Diuretics', 'SGLT2 inhibitors'],
    prevention: ['Control hypertension/CAD/diabetes', 'Avoid excess salt'],
    redFlags: ['Rapid weight gain with edema', 'Breathlessness at rest', 'Low oxygen symptoms'],
  },
  stroke: {
    title: 'Stroke',
    aliases: ['stroke', 'brain stroke', 'cerebrovascular accident', 'cva'],
    symptoms: ['Face droop', 'Arm weakness', 'Speech difficulty', 'Sudden vision loss or imbalance'],
    management: ['Emergency stroke protocol', 'Risk factor control', 'Rehabilitation therapy'],
    tests: ['CT/MRI brain', 'Vascular imaging', 'Cardiac rhythm monitoring', 'Blood tests'],
    medications: ['Antiplatelets or anticoagulants depending cause', 'Statins', 'BP control medicines'],
    prevention: ['Control BP/diabetes/lipids', 'Treat atrial fibrillation', 'No smoking'],
    redFlags: ['Any sudden neurologic deficit needs emergency care immediately'],
  },
  epilepsy: {
    title: 'Epilepsy',
    aliases: ['epilepsy', 'seizure disorder', 'fits', 'convulsions'],
    symptoms: ['Recurrent unprovoked seizures', 'Temporary confusion', 'Loss of awareness'],
    management: ['Regular anti-seizure medication', 'Sleep hygiene', 'Avoid known triggers', 'Neurology follow-up'],
    tests: ['EEG', 'MRI brain', 'Metabolic panel where needed'],
    medications: ['Levetiracetam', 'Valproate', 'Lamotrigine', 'Carbamazepine (condition-specific)'],
    prevention: ['Adherence to medicines', 'Avoid sleep deprivation and alcohol excess'],
    redFlags: ['Seizure >5 minutes', 'Repeated seizures without recovery', 'Injury with seizure'],
  },
  migraine: {
    title: 'Migraine',
    aliases: ['migraine', 'one sided headache', 'vascular headache'],
    symptoms: ['Moderate/severe throbbing headache', 'Nausea', 'Light/sound sensitivity', 'Aura in some patients'],
    management: ['Trigger diary', 'Hydration and sleep regulation', 'Acute abortive therapy', 'Preventive therapy if frequent'],
    tests: ['Clinical diagnosis; imaging only when red flags present'],
    medications: ['NSAIDs/triptans (acute)', 'Topiramate/beta blockers/CGRP meds (prevention)'],
    prevention: ['Regular sleep and meals', 'Limit trigger foods', 'Stress reduction'],
    redFlags: ['Thunderclap headache', 'Neurologic deficits', 'Fever with neck stiffness'],
  },
  hypothyroidism: {
    title: 'Hypothyroidism',
    aliases: ['hypothyroid', 'hypothyroidism', 'underactive thyroid'],
    symptoms: ['Fatigue', 'Weight gain', 'Constipation', 'Cold intolerance', 'Dry skin'],
    management: ['Levothyroxine replacement', 'Dose titration by TSH', 'Regular follow-up'],
    tests: ['TSH', 'Free T4', 'Thyroid antibodies when indicated'],
    medications: ['Levothyroxine'],
    prevention: ['Do not skip doses', 'Periodic thyroid testing'],
    redFlags: ['Severe drowsiness/confusion', 'Low body temperature', 'Worsening breathlessness'],
  },
  hyperthyroidism: {
    title: 'Hyperthyroidism',
    aliases: ['hyperthyroid', 'hyperthyroidism', 'overactive thyroid', 'thyrotoxicosis'],
    symptoms: ['Weight loss', 'Palpitations', 'Heat intolerance', 'Anxiety', 'Tremor'],
    management: ['Beta blocker symptom control', 'Antithyroid therapy', 'Endocrine follow-up'],
    tests: ['TSH', 'Free T4/T3', 'Thyroid uptake/scan when indicated'],
    medications: ['Methimazole/carbimazole', 'Propylthiouracil in selected settings', 'Beta blockers'],
    prevention: ['Regular labs and dose adjustment'],
    redFlags: ['High fever with agitation', 'Fast irregular pulse', 'Confusion'],
  },
  anemia: {
    title: 'Anemia',
    aliases: ['anemia', 'anaemia', 'low hemoglobin', 'iron deficiency'],
    symptoms: ['Fatigue', 'Pallor', 'Exertional breathlessness', 'Dizziness'],
    management: ['Find root cause', 'Nutrient replacement', 'Diet correction', 'Follow-up CBC'],
    tests: ['CBC', 'Ferritin and iron studies', 'B12/Folate', 'Reticulocyte count'],
    medications: ['Iron supplements', 'B12/Folate replacement', 'Cause-specific treatment'],
    prevention: ['Balanced nutrient-rich diet', 'Screening in high-risk groups'],
    redFlags: ['Chest pain', 'Fainting', 'Blood in stool', 'Severe weakness'],
  },
  depression: {
    title: 'Depression',
    aliases: ['depression', 'major depressive disorder', 'low mood'],
    symptoms: ['Persistent low mood', 'Loss of interest', 'Sleep/appetite changes', 'Low energy', 'Hopelessness'],
    management: ['Psychotherapy', 'Lifestyle structure', 'Medication when indicated', 'Regular mental health follow-up'],
    tests: ['Clinical screening tools and psychiatric evaluation'],
    medications: ['SSRIs/SNRIs or other antidepressants per psychiatrist'],
    prevention: ['Routine sleep, activity, social support, early help seeking'],
    redFlags: ['Self-harm thoughts', 'Suicidal ideas', 'Inability to care for self'],
  },
  anxiety: {
    title: 'Anxiety Disorders',
    aliases: ['anxiety', 'panic', 'panic attack', 'generalized anxiety'],
    symptoms: ['Excessive worry', 'Restlessness', 'Palpitations', 'Sleep disturbance', 'Panic episodes'],
    management: ['CBT-based coping', 'Breathing/relaxation training', 'Trigger management', 'Therapy +/- medication'],
    tests: ['Clinical evaluation; rule out thyroid/cardiac contributors if needed'],
    medications: ['SSRIs/SNRIs', 'Short-term anxiolytics in selected cases'],
    prevention: ['Stress hygiene', 'Sleep regularity', 'Caffeine moderation'],
    redFlags: ['Suicidal thoughts', 'Chest pain or fainting needing urgent exclusion of medical causes'],
  },
  osteoarthritis: {
    title: 'Osteoarthritis',
    aliases: ['osteoarthritis', 'oa knee', 'joint wear and tear', 'knee arthritis'],
    symptoms: ['Joint pain with activity', 'Morning stiffness <30 min', 'Reduced range of motion'],
    management: ['Weight reduction', 'Strengthening exercises', 'Physiotherapy', 'Pain control plan'],
    tests: ['Clinical exam', 'X-ray as needed'],
    medications: ['Topical/oral NSAIDs', 'Acetaminophen', 'Injections in selected cases'],
    prevention: ['Joint-friendly activity', 'Healthy body weight'],
    redFlags: ['Hot swollen joint with fever', 'Inability to bear weight after injury'],
  },
  rheumatoid_arthritis: {
    title: 'Rheumatoid Arthritis',
    aliases: ['rheumatoid arthritis', 'ra arthritis', 'inflammatory arthritis'],
    symptoms: ['Symmetric small joint pain', 'Morning stiffness >1 hour', 'Joint swelling'],
    management: ['Early rheumatology care', 'DMARD therapy', 'Exercise and joint protection'],
    tests: ['RF/anti-CCP', 'ESR/CRP', 'Imaging as needed'],
    medications: ['Methotrexate and other DMARDs', 'Biologics in selected patients'],
    prevention: ['Early diagnosis and adherence reduce joint damage'],
    redFlags: ['Severe flare with systemic symptoms', 'Breathing issues/chest pain'],
  },
  gerd: {
    title: 'GERD',
    aliases: ['gerd', 'acid reflux', 'acidity', 'heartburn', 'reflux'],
    symptoms: ['Heartburn', 'Sour regurgitation', 'Chest discomfort after meals', 'Night cough in some'],
    management: ['Small frequent meals', 'Avoid late-night eating', 'Weight control', 'Head-end elevation at night'],
    tests: ['Clinical diagnosis', 'Endoscopy if alarm symptoms', 'pH testing in selected cases'],
    medications: ['Proton pump inhibitors', 'H2 blockers', 'Antacids'],
    prevention: ['Avoid trigger foods', 'Reduce weight', 'Avoid tobacco/alcohol excess'],
    redFlags: ['Difficulty swallowing', 'GI bleeding', 'Unintentional weight loss'],
  },
  peptic_ulcer: {
    title: 'Peptic Ulcer Disease',
    aliases: ['peptic ulcer', 'stomach ulcer', 'duodenal ulcer'],
    symptoms: ['Burning upper abdominal pain', 'Bloating', 'Nausea'],
    management: ['Eradicate H. pylori if present', 'Avoid NSAID overuse', 'Acid suppression therapy'],
    tests: ['H. pylori tests', 'Upper GI endoscopy'],
    medications: ['PPIs', 'Antibiotics for H. pylori'],
    prevention: ['Avoid smoking/alcohol excess', 'Careful NSAID use'],
    redFlags: ['Black stools', 'Vomiting blood', 'Severe sudden abdominal pain'],
  },
  ibs: {
    title: 'Irritable Bowel Syndrome',
    aliases: ['ibs', 'irritable bowel syndrome', 'functional bowel disorder'],
    symptoms: ['Recurrent abdominal pain', 'Bloating', 'Constipation and/or diarrhea'],
    management: ['Food trigger identification', 'Fiber and hydration plan', 'Stress management', 'Symptom-targeted medicines'],
    tests: ['Clinical criteria with limited tests to rule out red flags'],
    medications: ['Antispasmodics', 'Laxatives/antidiarrheals based on subtype'],
    prevention: ['Regular meal timing', 'Low FODMAP trial with guidance'],
    redFlags: ['Blood in stool', 'Night-time symptoms', 'Weight loss', 'Anemia'],
  },
  pneumonia: {
    title: 'Pneumonia',
    aliases: ['pneumonia', 'lung infection', 'chest infection'],
    symptoms: ['Fever', 'Cough with sputum', 'Chest pain', 'Shortness of breath'],
    management: ['Prompt clinical review', 'Antibiotics when bacterial', 'Hydration and rest', 'Oxygen support if needed'],
    tests: ['Chest X-ray', 'CBC', 'Oxygen saturation', 'Sputum tests in selected cases'],
    medications: ['Antibiotics by protocol', 'Antipyretics', 'Supportive therapy'],
    prevention: ['Vaccination', 'Hand hygiene', 'Smoking cessation'],
    redFlags: ['Low oxygen', 'Confusion', 'Rapid breathing', 'Persistent high fever'],
  },
  tuberculosis: {
    title: 'Tuberculosis',
    aliases: ['tb', 'tuberculosis', 'pulmonary tb'],
    symptoms: ['Cough >2-3 weeks', 'Weight loss', 'Night sweats', 'Fever', 'Blood in sputum sometimes'],
    management: ['Confirm diagnosis early', 'Start full anti-TB regimen', 'Strict adherence to complete course'],
    tests: ['Sputum AFB/NAAT', 'Chest X-ray', 'Culture and susceptibility'],
    medications: ['Standard multidrug anti-TB therapy as per protocol'],
    prevention: ['Screen contacts', 'Ventilation and masking in high-risk settings'],
    redFlags: ['Coughing blood', 'Breathlessness', 'Severe weakness/dehydration'],
  },
  dengue: {
    title: 'Dengue',
    aliases: ['dengue', 'breakbone fever'],
    symptoms: ['High fever', 'Severe body pain', 'Headache behind eyes', 'Nausea', 'Rash'],
    management: ['Hydration and monitoring', 'Avoid NSAIDs like ibuprofen', 'Platelet and hematocrit follow-up'],
    tests: ['NS1 antigen/PCR early', 'IgM later', 'CBC with platelet trend'],
    medications: ['Paracetamol for fever', 'Fluids'],
    prevention: ['Mosquito bite prevention', 'Stagnant water control'],
    redFlags: ['Bleeding', 'Persistent vomiting', 'Severe abdominal pain', 'Drowsiness'],
  },
  uti: {
    title: 'Urinary Tract Infection (UTI)',
    aliases: ['uti', 'urinary tract infection', 'bladder infection', 'cystitis', 'burning urination'],
    symptoms: ['Burning on urination', 'Frequent urge to urinate', 'Lower abdominal pain', 'Cloudy or bloody urine'],
    management: ['Complete antibiotic course', 'Adequate hydration', 'Urinate after intercourse', 'Avoid irritants'],
    tests: ['Urinalysis', 'Urine culture', 'Imaging if recurrent'],
    medications: ['Antibiotics per culture/sensitivity', 'Urinary analgesics short-term'],
    prevention: ['Stay hydrated', 'Regular voiding', 'Good hygiene', 'Cranberry supplements may help'],
    redFlags: ['High fever with flank pain', 'Nausea/vomiting', 'Recurrent infections', 'Blood in urine'],
  },
  fatty_liver: {
    title: 'Fatty Liver Disease (NAFLD)',
    aliases: ['fatty liver', 'nafld', 'liver disease', 'hepatic steatosis'],
    symptoms: ['Often no symptoms', 'Fatigue', 'Upper right abdominal discomfort', 'Possible elevated liver enzymes'],
    management: ['Weight loss 7-10%', 'Mediterranean diet', 'Regular exercise', 'Alcohol avoidance', 'Diabetes control'],
    tests: ['Liver function tests', 'Ultrasound', 'Fibroscan', 'Liver biopsy in selected cases'],
    medications: ['No approved specific drug; treat underlying conditions', 'Vitamin E in selected cases'],
    prevention: ['Healthy weight', 'Limit sugar and processed foods', 'Regular exercise', 'Avoid excess alcohol'],
    redFlags: ['Jaundice', 'Severe abdominal swelling', 'Confusion', 'Dark urine with pale stools'],
  },
  parkinsons: {
    title: "Parkinson's Disease",
    aliases: ['parkinsons', 'parkinson disease', 'tremor disorder'],
    symptoms: ['Resting tremor', 'Bradykinesia (slowness)', 'Rigidity', 'Postural instability', 'Shuffling gait'],
    management: ['Levodopa therapy', 'Physical/occupational therapy', 'Exercise program', 'Neurology follow-up'],
    tests: ['Clinical diagnosis', 'DaTscan in uncertain cases', 'Response to levodopa trial'],
    medications: ['Levodopa/carbidopa', 'Dopamine agonists', 'MAO-B inhibitors', 'COMT inhibitors'],
    prevention: ['Exercise may reduce risk', 'Caffeine association noted in studies'],
    redFlags: ['Falls with injury', 'Swallowing difficulty', 'Severe medication side effects', 'Hallucinations'],
  },
  alzheimers: {
    title: "Alzheimer's Disease / Dementia",
    aliases: ['alzheimers', 'alzheimer', 'dementia', 'memory loss', 'cognitive decline'],
    symptoms: ['Progressive memory loss', 'Confusion', 'Difficulty with daily tasks', 'Language problems', 'Mood changes'],
    management: ['Cognitive stimulation', 'Structured routine', 'Caregiver support', 'Safe environment', 'Medication adherence'],
    tests: ['Cognitive screening (MMSE, MoCA)', 'Brain MRI', 'Rule out reversible causes'],
    medications: ['Cholinesterase inhibitors (donepezil)', 'Memantine', 'Treat behavioral symptoms'],
    prevention: ['Cardiovascular health', 'Mental stimulation', 'Social engagement', 'Physical activity'],
    redFlags: ['Wandering behavior', 'Severe agitation', 'Self-neglect', 'Caregiver burnout'],
  },
  uti_complicated: {
    title: 'Pyelonephritis (Kidney Infection)',
    aliases: ['pyelonephritis', 'kidney infection', 'upper uti'],
    symptoms: ['High fever with chills', 'Flank pain', 'Nausea/vomiting', 'Burning urination'],
    management: ['Prompt antibiotics', 'Hospitalization if severe', 'Hydration', 'Pain control'],
    tests: ['Urinalysis and culture', 'Blood cultures', 'Kidney imaging if complications'],
    medications: ['Broad-spectrum IV antibiotics initially', 'Oral step-down therapy'],
    prevention: ['Treat lower UTIs promptly', 'Address urinary obstruction if present'],
    redFlags: ['Sepsis signs', 'Persistent high fever', 'Severe dehydration', 'Obstruction'],
  },
  influenza: {
    title: 'Influenza (Flu)',
    aliases: ['flu', 'influenza', 'seasonal flu'],
    symptoms: ['Sudden high fever', 'Body aches', 'Dry cough', 'Sore throat', 'Fatigue'],
    management: ['Rest and hydration', 'Antivirals within 48 hours if high risk', 'Symptomatic relief'],
    tests: ['Clinical diagnosis', 'Rapid flu test or PCR if needed'],
    medications: ['Oseltamivir (Tamiflu) in select cases', 'Acetaminophen/NSAIDs for fever'],
    prevention: ['Annual flu vaccine', 'Hand hygiene', 'Avoid close contact with sick'],
    redFlags: ['Difficulty breathing', 'Persistent high fever >3 days', 'Confusion', 'Chest pain'],
  },
  covid19: {
    title: 'COVID-19',
    aliases: ['covid', 'covid 19', 'coronavirus', 'sars cov 2'],
    symptoms: ['Fever', 'Cough', 'Loss of taste/smell', 'Breathlessness', 'Fatigue', 'Body aches'],
    management: ['Isolation', 'Monitoring oxygen levels', 'Antivirals in high-risk early cases', 'Supportive care'],
    tests: ['RT-PCR or rapid antigen test', 'Pulse oximetry', 'Chest imaging if severe'],
    medications: ['Paxlovid in early high-risk cases', 'Dexamethasone if oxygen needed', 'Remdesivir in hospitalized'],
    prevention: ['Vaccination', 'Masking in high-risk settings', 'Hand hygiene', 'Ventilation'],
    redFlags: ['Oxygen <94%', 'Severe breathlessness', 'Chest pain', 'Confusion', 'Blue lips'],
  },
};

const symptomHints = [
  { symptom: 'frequent urination', hints: ['diabetes', 'urinary tract issues', 'uti'] },
  { symptom: 'excessive thirst', hints: ['diabetes', 'dehydration'] },
  { symptom: 'wheezing', hints: ['asthma', 'copd'] },
  { symptom: 'palpitations', hints: ['hyperthyroidism', 'anxiety', 'arrhythmia'] },
  { symptom: 'fatigue', hints: ['anemia', 'hypothyroidism', 'depression', 'diabetes', 'covid'] },
  { symptom: 'swelling legs', hints: ['heart failure', 'kidney disease', 'venous disease'] },
  { symptom: 'chest tightness', hints: ['asthma', 'anxiety', 'heart disease'] },
  { symptom: 'headache', hints: ['migraine', 'hypertension', 'sinusitis'] },
  { symptom: 'joint pain', hints: ['osteoarthritis', 'rheumatoid arthritis', 'viral illness'] },
  { symptom: 'acid reflux', hints: ['gerd', 'peptic disease'] },
  { symptom: 'burning urination', hints: ['uti', 'kidney infection'] },
  { symptom: 'fever', hints: ['infection', 'flu', 'covid', 'dengue', 'uti', 'pneumonia'] },
  { symptom: 'cough', hints: ['asthma', 'copd', 'pneumonia', 'tb', 'covid', 'flu'] },
  { symptom: 'memory loss', hints: ['alzheimers', 'dementia', 'depression'] },
  { symptom: 'tremor', hints: ['parkinsons', 'essential tremor', 'hyperthyroidism'] },
  { symptom: 'weight loss', hints: ['hyperthyroidism', 'diabetes', 'tb', 'cancer screening needed'] },
  { symptom: 'abdominal pain', hints: ['gerd', 'peptic ulcer', 'ibs', 'appendicitis - seek urgent care'] },
];

module.exports = { diseaseData, symptomHints };
